version: "2"

services:
  voting-app:
    image: tomverelst/voting-app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    restart: always
    environment:
      - "constraint:type==frontend"

  result-app:
    image: tomverelst/result-app
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier
    restart: always
    environment:
      - "constraint:type==frontend"

  worker:
    image: tomverelst/worker
    networks:
      - back-tier
    restart: always
    environment:
      - "constraint:type==backend"

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier
    restart: always
    environment:
      - "constraint:type==backend"

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    restart: always
    environment:
      - "constraint:type==backend"
      - "constraint:storage==ssd"

volumes:
  db-data:

networks:
  front-tier:
    external:
      name: front-tier
  back-tier:
    external:
      name: back-tier
